### ISSUE TITLE
Typescript type mismatch for nkruntime.Context.vars

### ISSUE THREAD

**Issue by Ratio2** [heroiclabs/nakama-common#132] opened 2023-09-10 07:36 UTC
nakama 3.17.1
nakama-runtime 1.28.1

nkruntime.Context.vars undefined in my setup, but typescript definition don't allow optional

**Comment by Ratio2** [comment] 2023-09-11 07:42
Seems problem with other properties too. Only node, version and env properties defined.

**Comment by zyro** [comment] 2024-08-11 15:46
We've been unable to reproduce this issue, so will close this now. Please note that not all `Context` elements are populated for every operation - for example `matchId` is only available in contexts within authoritative multiplayer match handlers.

If it re-occurs with the latest version of Nakama (3.23.0+ and `nakama-common` 1.33.0+) please re-open this and provide a complete minimal reproducible test case.

**Closed** 2024-08-11 16:51 UTC
